export interface AddressEntry {
  label: string
  abbr: string
  aliases?: string[]
}

export const STATE_ABBREVIATIONS: AddressEntry[] = [
  { label: 'Alabama', abbr: 'AL' },
  { label: 'Alaska', abbr: 'AK' },
  { label: 'Arizona', abbr: 'AZ' },
  { label: 'Arkansas', abbr: 'AR' },
  { label: 'California', abbr: 'CA' },
  { label: 'Colorado', abbr: 'CO' },
  { label: 'Connecticut', abbr: 'CT' },
  { label: 'Delaware', abbr: 'DE' },
  { label: 'District of Columbia', abbr: 'DC', aliases: ['Washington DC', 'D.C.'] },
  { label: 'Florida', abbr: 'FL' },
  { label: 'Georgia', abbr: 'GA' },
  { label: 'Hawaii', abbr: 'HI' },
  { label: 'Idaho', abbr: 'ID' },
  { label: 'Illinois', abbr: 'IL' },
  { label: 'Indiana', abbr: 'IN' },
  { label: 'Iowa', abbr: 'IA' },
  { label: 'Kansas', abbr: 'KS' },
  { label: 'Kentucky', abbr: 'KY' },
  { label: 'Louisiana', abbr: 'LA' },
  { label: 'Maine', abbr: 'ME' },
  { label: 'Maryland', abbr: 'MD' },
  { label: 'Massachusetts', abbr: 'MA' },
  { label: 'Michigan', abbr: 'MI' },
  { label: 'Minnesota', abbr: 'MN' },
  { label: 'Mississippi', abbr: 'MS' },
  { label: 'Missouri', abbr: 'MO' },
  { label: 'Montana', abbr: 'MT' },
  { label: 'Nebraska', abbr: 'NE' },
  { label: 'Nevada', abbr: 'NV' },
  { label: 'New Hampshire', abbr: 'NH' },
  { label: 'New Jersey', abbr: 'NJ' },
  { label: 'New Mexico', abbr: 'NM' },
  { label: 'New York', abbr: 'NY' },
  { label: 'North Carolina', abbr: 'NC' },
  { label: 'North Dakota', abbr: 'ND' },
  { label: 'Ohio', abbr: 'OH' },
  { label: 'Oklahoma', abbr: 'OK' },
  { label: 'Oregon', abbr: 'OR' },
  { label: 'Pennsylvania', abbr: 'PA' },
  { label: 'Rhode Island', abbr: 'RI' },
  { label: 'South Carolina', abbr: 'SC' },
  { label: 'South Dakota', abbr: 'SD' },
  { label: 'Tennessee', abbr: 'TN' },
  { label: 'Texas', abbr: 'TX' },
  { label: 'Utah', abbr: 'UT' },
  { label: 'Vermont', abbr: 'VT' },
  { label: 'Virginia', abbr: 'VA' },
  { label: 'Washington', abbr: 'WA' },
  { label: 'West Virginia', abbr: 'WV' },
  { label: 'Wisconsin', abbr: 'WI' },
  { label: 'Wyoming', abbr: 'WY' },
  { label: 'Puerto Rico', abbr: 'PR' },
  { label: 'U.S. Virgin Islands', abbr: 'VI', aliases: ['Virgin Islands'] },
  { label: 'Guam', abbr: 'GU' },
  { label: 'American Samoa', abbr: 'AS' },
  { label: 'Northern Mariana Islands', abbr: 'MP', aliases: ['Mariana Islands'] },
]

export const STREET_SUFFIXES: AddressEntry[] = [
  { label: 'Alley', abbr: 'ALY', aliases: ['Alleys'] },
  { label: 'Annex', abbr: 'ANX', aliases: ['Anex', 'Annx'] },
  { label: 'Arcade', abbr: 'ARC' },
  { label: 'Avenue', abbr: 'AVE', aliases: ['Av', 'Aven', 'Avenu'] },
  { label: 'Bayou', abbr: 'BYU' },
  { label: 'Beach', abbr: 'BCH' },
  { label: 'Bend', abbr: 'BND' },
  { label: 'Bluff', abbr: 'BLF' },
  { label: 'Bluffs', abbr: 'BLFS' },
  { label: 'Bottom', abbr: 'BTM' },
  { label: 'Boulevard', abbr: 'BLVD', aliases: ['Boul', 'Boulv'] },
  { label: 'Branch', abbr: 'BR' },
  { label: 'Bridge', abbr: 'BRG' },
  { label: 'Brook', abbr: 'BRK' },
  { label: 'Brooks', abbr: 'BRKS' },
  { label: 'Burg', abbr: 'BG' },
  { label: 'Burgs', abbr: 'BGS' },
  { label: 'Bypass', abbr: 'BYP' },
  { label: 'Camp', abbr: 'CP' },
  { label: 'Cape', abbr: 'CPE' },
  { label: 'Canyon', abbr: 'CYN' },
  { label: 'Causeway', abbr: 'CSWY' },
  { label: 'Center', abbr: 'CTR' },
  { label: 'Centers', abbr: 'CTRS' },
  { label: 'Circle', abbr: 'CIR' },
  { label: 'Circles', abbr: 'CIRS' },
  { label: 'Cliff', abbr: 'CLF' },
  { label: 'Cliffs', abbr: 'CLFS' },
  { label: 'Club', abbr: 'CLB' },
  { label: 'Common', abbr: 'CMN' },
  { label: 'Commons', abbr: 'CMNS' },
  { label: 'Corner', abbr: 'COR' },
  { label: 'Corners', abbr: 'CORS' },
  { label: 'Course', abbr: 'CRSE' },
  { label: 'Court', abbr: 'CT' },
  { label: 'Courts', abbr: 'CTS' },
  { label: 'Cove', abbr: 'CV' },
  { label: 'Coves', abbr: 'CVS' },
  { label: 'Creek', abbr: 'CRK' },
  { label: 'Crescent', abbr: 'CRES' },
  { label: 'Crest', abbr: 'CRST' },
  { label: 'Crossing', abbr: 'XING' },
  { label: 'Crossroad', abbr: 'XRD' },
  { label: 'Crossroads', abbr: 'XRDS' },
  { label: 'Curve', abbr: 'CURV' },
  { label: 'Dale', abbr: 'DL' },
  { label: 'Dam', abbr: 'DM' },
  { label: 'Divide', abbr: 'DV', aliases: ['Div'] },
  { label: 'Drive', abbr: 'DR' },
  { label: 'Drives', abbr: 'DRS' },
  { label: 'Estate', abbr: 'EST' },
  { label: 'Estates', abbr: 'ESTS' },
  { label: 'Expressway', abbr: 'EXPY' },
  { label: 'Extension', abbr: 'EXT' },
  { label: 'Extensions', abbr: 'EXTS' },
  { label: 'Falls', abbr: 'FLS' },
  { label: 'Ferry', abbr: 'FRY' },
  { label: 'Field', abbr: 'FLD' },
  { label: 'Fields', abbr: 'FLDS' },
  { label: 'Flat', abbr: 'FLT' },
  { label: 'Flats', abbr: 'FLTS' },
  { label: 'Ford', abbr: 'FRD' },
  { label: 'Fords', abbr: 'FRDS' },
  { label: 'Forest', abbr: 'FRST' },
  { label: 'Forge', abbr: 'FRG' },
  { label: 'Forges', abbr: 'FRGS' },
  { label: 'Fork', abbr: 'FRK' },
  { label: 'Forks', abbr: 'FRKS' },
  { label: 'Fort', abbr: 'FT' },
  { label: 'Freeway', abbr: 'FWY' },
  { label: 'Garden', abbr: 'GDN' },
  { label: 'Gardens', abbr: 'GDNS' },
  { label: 'Gateway', abbr: 'GTWY' },
  { label: 'Glen', abbr: 'GLN' },
  { label: 'Glens', abbr: 'GLNS' },
  { label: 'Green', abbr: 'GRN' },
  { label: 'Greens', abbr: 'GRNS' },
  { label: 'Grove', abbr: 'GRV' },
  { label: 'Groves', abbr: 'GRVS' },
  { label: 'Harbor', abbr: 'HBR' },
  { label: 'Harbors', abbr: 'HBRS' },
  { label: 'Haven', abbr: 'HVN' },
  { label: 'Heights', abbr: 'HTS' },
  { label: 'Highway', abbr: 'HWY' },
  { label: 'Hill', abbr: 'HL' },
  { label: 'Hills', abbr: 'HLS' },
  { label: 'Hollow', abbr: 'HOLW' },
  { label: 'Island', abbr: 'IS' },
  { label: 'Islands', abbr: 'ISS' },
  { label: 'Isle', abbr: 'ISLE' },
  { label: 'Junction', abbr: 'JCT' },
  { label: 'Junctions', abbr: 'JCTS' },
  { label: 'Key', abbr: 'KY' },
  { label: 'Keys', abbr: 'KYS' },
  { label: 'Knoll', abbr: 'KNL' },
  { label: 'Knolls', abbr: 'KNLS' },
  { label: 'Lake', abbr: 'LK' },
  { label: 'Lakes', abbr: 'LKS' },
  { label: 'Landing', abbr: 'LNDG' },
  { label: 'Lane', abbr: 'LN' },
  { label: 'Light', abbr: 'LGT' },
  { label: 'Lights', abbr: 'LGTS' },
  { label: 'Loaf', abbr: 'LF' },
  { label: 'Lock', abbr: 'LCK' },
  { label: 'Locks', abbr: 'LCKS' },
  { label: 'Lodge', abbr: 'LDG' },
  { label: 'Loop', abbr: 'LOOP' },
  { label: 'Mall', abbr: 'MALL' },
  { label: 'Manor', abbr: 'MNR' },
  { label: 'Manors', abbr: 'MNRS' },
  { label: 'Meadow', abbr: 'MDW' },
  { label: 'Meadows', abbr: 'MDWS' },
  { label: 'Mill', abbr: 'ML' },
  { label: 'Mills', abbr: 'MLS' },
  { label: 'Mission', abbr: 'MSN' },
  { label: 'Motorway', abbr: 'MTWY' },
  { label: 'Mount', abbr: 'MT' },
  { label: 'Mountain', abbr: 'MTN' },
  { label: 'Mountains', abbr: 'MTNS' },
  { label: 'Neck', abbr: 'NCK' },
  { label: 'Orchard', abbr: 'ORCH' },
  { label: 'Oval', abbr: 'OVAL' },
  { label: 'Overpass', abbr: 'OPAS' },
  { label: 'Park', abbr: 'PARK' },
  { label: 'Parkway', abbr: 'PKWY' },
  { label: 'Pass', abbr: 'PASS' },
  { label: 'Path', abbr: 'PATH' },
  { label: 'Pike', abbr: 'PIKE' },
  { label: 'Pine', abbr: 'PNE' },
  { label: 'Pines', abbr: 'PNES' },
  { label: 'Place', abbr: 'PL' },
  { label: 'Plain', abbr: 'PLN' },
  { label: 'Plains', abbr: 'PLNS' },
  { label: 'Plaza', abbr: 'PLZ' },
  { label: 'Point', abbr: 'PT' },
  { label: 'Points', abbr: 'PTS' },
  { label: 'Port', abbr: 'PRT' },
  { label: 'Ports', abbr: 'PRTS' },
  { label: 'Prairie', abbr: 'PR' },
  { label: 'Radial', abbr: 'RADL' },
  { label: 'Ramp', abbr: 'RAMP' },
  { label: 'Ranch', abbr: 'RNCH' },
  { label: 'Rapid', abbr: 'RPD' },
  { label: 'Rapids', abbr: 'RPDS' },
  { label: 'Rest', abbr: 'RST' },
  { label: 'Ridge', abbr: 'RDG' },
  { label: 'Ridges', abbr: 'RDGS' },
  { label: 'River', abbr: 'RIV' },
  { label: 'Road', abbr: 'RD' },
  { label: 'Roads', abbr: 'RDS' },
  { label: 'Route', abbr: 'RTE' },
  { label: 'Row', abbr: 'ROW' },
  { label: 'Run', abbr: 'RUN' },
  { label: 'Shoal', abbr: 'SHL' },
  { label: 'Shoals', abbr: 'SHLS' },
  { label: 'Shore', abbr: 'SHR' },
  { label: 'Shores', abbr: 'SHRS' },
  { label: 'Skyway', abbr: 'SKWY' },
  { label: 'Spring', abbr: 'SPG' },
  { label: 'Springs', abbr: 'SPGS' },
  { label: 'Spur', abbr: 'SPUR' },
  { label: 'Spurs', abbr: 'SPUR' },
  { label: 'Square', abbr: 'SQ' },
  { label: 'Squares', abbr: 'SQS' },
  { label: 'Station', abbr: 'STA' },
  { label: 'Stravenue', abbr: 'STRA' },
  { label: 'Stream', abbr: 'STRM' },
  { label: 'Street', abbr: 'ST', aliases: ['Str', 'Streets'] },
  { label: 'Streets', abbr: 'STS' },
  { label: 'Summit', abbr: 'SMT' },
  { label: 'Terrace', abbr: 'TER' },
  { label: 'Throughway', abbr: 'TRWY' },
  { label: 'Trace', abbr: 'TRCE' },
  { label: 'Track', abbr: 'TRAK' },
  { label: 'Trafficway', abbr: 'TRFY' },
  { label: 'Trail', abbr: 'TRL' },
  { label: 'Tunnel', abbr: 'TUNL' },
  { label: 'Turnpike', abbr: 'TPKE' },
  { label: 'Underpass', abbr: 'UPAS' },
  { label: 'Union', abbr: 'UN' },
  { label: 'Unions', abbr: 'UNS' },
  { label: 'Valley', abbr: 'VLY' },
  { label: 'Valleys', abbr: 'VLYS' },
  { label: 'Viaduct', abbr: 'VIA' },
  { label: 'View', abbr: 'VW' },
  { label: 'Views', abbr: 'VWS' },
  { label: 'Village', abbr: 'VLG' },
  { label: 'Villages', abbr: 'VLGS' },
  { label: 'Ville', abbr: 'VL' },
  { label: 'Vista', abbr: 'VIS' },
  { label: 'Walk', abbr: 'WALK' },
  { label: 'Walks', abbr: 'WALK' },
  { label: 'Wall', abbr: 'WALL' },
  { label: 'Way', abbr: 'WAY' },
  { label: 'Ways', abbr: 'WAYS' },
  { label: 'Well', abbr: 'WL' },
  { label: 'Wells', abbr: 'WLS' },
]

export const SECONDARY_UNIT_ABBREVIATIONS: AddressEntry[] = [
  { label: 'Apartment', abbr: 'APT' },
  { label: 'Basement', abbr: 'BSMT' },
  { label: 'Building', abbr: 'BLDG' },
  { label: 'Department', abbr: 'DEPT' },
  { label: 'Floor', abbr: 'FL' },
  { label: 'Front', abbr: 'FRNT' },
  { label: 'Hangar', abbr: 'HNGR' },
  { label: 'Key', abbr: 'KEY' },
  { label: 'Lobby', abbr: 'LBBY' },
  { label: 'Lot', abbr: 'LOT' },
  { label: 'Lower', abbr: 'LOWR' },
  { label: 'Office', abbr: 'OFC' },
  { label: 'Penthouse', abbr: 'PH' },
  { label: 'Pier', abbr: 'PIER' },
  { label: 'Rear', abbr: 'REAR' },
  { label: 'Room', abbr: 'RM' },
  { label: 'Side', abbr: 'SIDE' },
  { label: 'Slip', abbr: 'SLIP' },
  { label: 'Space', abbr: 'SPC' },
  { label: 'Stop', abbr: 'STOP' },
  { label: 'Suite', abbr: 'STE' },
  { label: 'Trailer', abbr: 'TRLR' },
  { label: 'Unit', abbr: 'UNIT' },
  { label: 'Upper', abbr: 'UPPR' },
]

export const DIRECTIONAL_ABBREVIATIONS: AddressEntry[] = [
  { label: 'North', abbr: 'N', aliases: ['Norte'] },
  { label: 'South', abbr: 'S', aliases: ['Sur'] },
  { label: 'East', abbr: 'E', aliases: ['Este'] },
  { label: 'West', abbr: 'W', aliases: ['Oeste'] },
  { label: 'Northeast', abbr: 'NE', aliases: ['North East', 'Nor Este', 'Noreste'] },
  { label: 'Northwest', abbr: 'NW', aliases: ['North West', 'Nor Oeste', 'Noroeste'] },
  { label: 'Southeast', abbr: 'SE', aliases: ['South East', 'Sur Este', 'Sureste'] },
  { label: 'Southwest', abbr: 'SW', aliases: ['South West', 'Sur Oeste', 'Suroeste'] },
]
