/**
 * Códigos de área (area codes) del NANP asignados a EE. UU., territorios y no-geográficos.
 * Biblioteca local (no requiere API): el area code (los 3 dígitos tras el +1) indica el
 * estado/región de ORIGEN del número — una pista de dónde lo obtuvo la persona.
 *
 * Dataset compilado y verificado contra la lista oficial del NANP (Wikipedia/NANPA).
 * 383 entradas: 50 estados + DC + 6 territorios + no-geográficos (toll-free/premium).
 * Para actualizar: los area codes son estables; se agregan overlays ocasionalmente.
 */

export interface AreaCode {
  /** 3 dígitos, p.ej. "212". */
  code: string
  /** Abreviatura del estado/territorio. "" para no-geográficos. */
  stateAbbr: string
  /** Nombre completo del estado/territorio, o "No geográfico". */
  state: string
  /** Ciudad(es) principal(es) o región que cubre. */
  region: string
}

export const AREA_CODES: AreaCode[] = [
  { code: '201', stateAbbr: 'NJ', state: 'New Jersey', region: 'North-east New Jersey (Bergen County and Hudson County)' },
  { code: '202', stateAbbr: 'DC', state: 'District of Columbia', region: 'Washington, D.C.' },
  { code: '203', stateAbbr: 'CT', state: 'Connecticut', region: 'South-west Connecticut (Bridgeport, Danbury, New Haven, Waterbury)' },
  { code: '205', stateAbbr: 'AL', state: 'Alabama', region: 'Western and central Alabama (Birmingham, Tuscaloosa)' },
  { code: '206', stateAbbr: 'WA', state: 'Washington', region: 'Seattle area' },
  { code: '207', stateAbbr: 'ME', state: 'Maine', region: 'all' },
  { code: '208', stateAbbr: 'ID', state: 'Idaho', region: 'all' },
  { code: '209', stateAbbr: 'CA', state: 'California', region: 'Central California (Stockton, Modesto, Merced)' },
  { code: '210', stateAbbr: 'TX', state: 'Texas', region: 'San Antonio metropolitan area' },
  { code: '212', stateAbbr: 'NY', state: 'New York', region: 'New York City (Manhattan)' },
  { code: '213', stateAbbr: 'CA', state: 'California', region: 'Central Los Angeles' },
  { code: '214', stateAbbr: 'TX', state: 'Texas', region: 'Dallas metropolitan area' },
  { code: '215', stateAbbr: 'PA', state: 'Pennsylvania', region: 'Philadelphia area' },
  { code: '216', stateAbbr: 'OH', state: 'Ohio', region: 'Cleveland area' },
  { code: '217', stateAbbr: 'IL', state: 'Illinois', region: 'Central Illinois (Springfield, Champaign, Decatur)' },
  { code: '218', stateAbbr: 'MN', state: 'Minnesota', region: 'Northern Minnesota (Duluth, Bemidji, Brainerd)' },
  { code: '219', stateAbbr: 'IN', state: 'Indiana', region: 'Gary area (Northwest Indiana)' },
  { code: '220', stateAbbr: 'OH', state: 'Ohio', region: 'Central Ohio (suburban Columbus)' },
  { code: '223', stateAbbr: 'PA', state: 'Pennsylvania', region: 'South-central Pennsylvania (Harrisburg, Lancaster, York)' },
  { code: '224', stateAbbr: 'IL', state: 'Illinois', region: 'North and northwest suburbs of Chicago' },
  { code: '225', stateAbbr: 'LA', state: 'Louisiana', region: 'East-central Louisiana (Baton Rouge)' },
  { code: '227', stateAbbr: 'MD', state: 'Maryland', region: 'Western Maryland (Silver Spring, Hagerstown, Frederick)' },
  { code: '228', stateAbbr: 'MS', state: 'Mississippi', region: 'Gulfport, Biloxi, Pascagoula (southern Mississippi)' },
  { code: '229', stateAbbr: 'GA', state: 'Georgia', region: 'Southwestern Georgia (Albany, Valdosta)' },
  { code: '231', stateAbbr: 'MI', state: 'Michigan', region: 'Northwestern Michigan (Muskegon, Traverse City)' },
  { code: '234', stateAbbr: 'OH', state: 'Ohio', region: 'Northeastern Ohio (Akron, Canton, Youngstown)' },
  { code: '235', stateAbbr: 'MO', state: 'Missouri', region: 'Eastern Missouri (Columbia, Jefferson City, Cape Girardeau)' },
  { code: '239', stateAbbr: 'FL', state: 'Florida', region: 'Southwest Florida (Cape Coral, Fort Myers, Naples)' },
  { code: '240', stateAbbr: 'MD', state: 'Maryland', region: 'Western Maryland (Silver Spring, Waldorf, Hagerstown)' },
  { code: '248', stateAbbr: 'MI', state: 'Michigan', region: 'Oakland County' },
  { code: '251', stateAbbr: 'AL', state: 'Alabama', region: 'Mobile, Baldwin County (southwestern Alabama)' },
  { code: '252', stateAbbr: 'NC', state: 'North Carolina', region: 'Greenville, New Bern, Outer Banks, Rocky Mount' },
  { code: '253', stateAbbr: 'WA', state: 'Washington', region: 'Tacoma, Lakewood, Auburn (southern suburbs of Seattle)' },
  { code: '254', stateAbbr: 'TX', state: 'Texas', region: 'Waco, Killeen, Temple' },
  { code: '256', stateAbbr: 'AL', state: 'Alabama', region: 'Huntsville, Decatur, Gadsden (northern Alabama)' },
  { code: '260', stateAbbr: 'IN', state: 'Indiana', region: 'Fort Wayne (northeastern Indiana)' },
  { code: '262', stateAbbr: 'WI', state: 'Wisconsin', region: 'Racine, Kenosha, Waukesha (southeastern Wisconsin)' },
  { code: '267', stateAbbr: 'PA', state: 'Pennsylvania', region: 'Philadelphia and surrounding suburbs' },
  { code: '269', stateAbbr: 'MI', state: 'Michigan', region: 'Kalamazoo, Battle Creek (southwestern Michigan)' },
  { code: '270', stateAbbr: 'KY', state: 'Kentucky', region: 'Bowling Green, Owensboro, Paducah (western Kentucky)' },
  { code: '272', stateAbbr: 'PA', state: 'Pennsylvania', region: 'Scranton, Wilkes-Barre, Williamsport (Wyoming Valley)' },
  { code: '274', stateAbbr: 'WI', state: 'Wisconsin', region: 'Appleton, Green Bay, Oshkosh (northeastern Wisconsin)' },
  { code: '276', stateAbbr: 'VA', state: 'Virginia', region: 'Bristol, Abingdon (southwestern Virginia)' },
  { code: '279', stateAbbr: 'CA', state: 'California', region: 'Sacramento Metropolitan Area' },
  { code: '281', stateAbbr: 'TX', state: 'Texas', region: 'Houston area' },
  { code: '283', stateAbbr: 'OH', state: 'Ohio', region: 'Cincinnati area (southwestern Ohio)' },
  { code: '301', stateAbbr: 'MD', state: 'Maryland', region: 'Silver Spring, Rockville, Frederick (D.C. suburbs)' },
  { code: '302', stateAbbr: 'DE', state: 'Delaware', region: 'all' },
  { code: '303', stateAbbr: 'CO', state: 'Colorado', region: 'Denver, Boulder, Aurora (central Colorado)' },
  { code: '304', stateAbbr: 'WV', state: 'West Virginia', region: 'all' },
  { code: '305', stateAbbr: 'FL', state: 'Florida', region: 'Miami-Dade County and the Florida Keys' },
  { code: '307', stateAbbr: 'WY', state: 'Wyoming', region: 'all' },
  { code: '308', stateAbbr: 'NE', state: 'Nebraska', region: 'North Platte, Scottsbluff, Kearney (western Nebraska)' },
  { code: '309', stateAbbr: 'IL', state: 'Illinois', region: 'Peoria, Bloomington, Moline (west-central Illinois)' },
  { code: '310', stateAbbr: 'CA', state: 'California', region: 'West/coastal Los Angeles County (Beverly Hills, Malibu)' },
  { code: '312', stateAbbr: 'IL', state: 'Illinois', region: 'Downtown Chicago' },
  { code: '313', stateAbbr: 'MI', state: 'Michigan', region: 'Detroit, Dearborn' },
  { code: '314', stateAbbr: 'MO', state: 'Missouri', region: 'St. Louis and inner suburbs' },
  { code: '315', stateAbbr: 'NY', state: 'New York', region: 'Syracuse, Utica, Watertown (north-central NY)' },
  { code: '316', stateAbbr: 'KS', state: 'Kansas', region: 'Wichita metro' },
  { code: '317', stateAbbr: 'IN', state: 'Indiana', region: 'Indianapolis metro' },
  { code: '318', stateAbbr: 'LA', state: 'Louisiana', region: 'Shreveport, Monroe, Alexandria (northern Louisiana)' },
  { code: '319', stateAbbr: 'IA', state: 'Iowa', region: 'Cedar Rapids, Waterloo, Iowa City (eastern Iowa)' },
  { code: '320', stateAbbr: 'MN', state: 'Minnesota', region: 'St. Cloud, Willmar (central Minnesota)' },
  { code: '321', stateAbbr: 'FL', state: 'Florida', region: 'Orlando, Melbourne, Titusville (east-central Florida)' },
  { code: '323', stateAbbr: 'CA', state: 'California', region: 'Downtown Los Angeles and surrounding areas' },
  { code: '324', stateAbbr: 'FL', state: 'Florida', region: 'Jacksonville, St. Augustine (northeastern Florida)' },
  { code: '325', stateAbbr: 'TX', state: 'Texas', region: 'Abilene, San Angelo' },
  { code: '326', stateAbbr: 'OH', state: 'Ohio', region: 'Dayton, Springfield (southwestern Ohio)' },
  { code: '327', stateAbbr: 'AR', state: 'Arkansas', region: 'Texarkana, Jonesboro, Pine Bluff (southern/eastern Arkansas)' },
  { code: '329', stateAbbr: 'NY', state: 'New York', region: 'Hudson Valley (Dutchess, Orange, Rockland, Ulster counties)' },
  { code: '330', stateAbbr: 'OH', state: 'Ohio', region: 'Akron, Canton, Youngstown (northeastern Ohio)' },
  { code: '331', stateAbbr: 'IL', state: 'Illinois', region: 'Aurora, Naperville (western suburbs of Chicago)' },
  { code: '332', stateAbbr: 'NY', state: 'New York', region: 'New York City (Manhattan)' },
  { code: '334', stateAbbr: 'AL', state: 'Alabama', region: 'Montgomery, Auburn, Dothan (southeastern Alabama)' },
  { code: '336', stateAbbr: 'NC', state: 'North Carolina', region: 'Piedmont Triad (Greensboro, Winston-Salem, High Point)' },
  { code: '337', stateAbbr: 'LA', state: 'Louisiana', region: 'Lafayette, Lake Charles (southwestern Louisiana)' },
  { code: '339', stateAbbr: 'MA', state: 'Massachusetts', region: 'Eastern Massachusetts (suburbs of Boston)' },
  { code: '340', stateAbbr: 'VI', state: 'U.S. Virgin Islands', region: 'U.S. Virgin Islands (todo el territorio)' },
  { code: '341', stateAbbr: 'CA', state: 'California', region: 'East Bay (Oakland, Fremont, Hayward, Berkeley)' },
  { code: '346', stateAbbr: 'TX', state: 'Texas', region: 'Houston area' },
  { code: '347', stateAbbr: 'NY', state: 'New York', region: 'New York City (Bronx, Brooklyn, Queens, Staten Island)' },
  { code: '350', stateAbbr: 'CA', state: 'California', region: 'Stockton, Modesto, Merced (central California)' },
  { code: '351', stateAbbr: 'MA', state: 'Massachusetts', region: 'Northeastern Massachusetts' },
  { code: '352', stateAbbr: 'FL', state: 'Florida', region: 'Gainesville, Ocala (north-central Florida)' },
  { code: '353', stateAbbr: 'WI', state: 'Wisconsin', region: 'Madison, La Crosse, Beloit (southwestern Wisconsin)' },
  { code: '357', stateAbbr: 'CA', state: 'California', region: 'Fresno, Visalia (San Joaquin Valley)' },
  { code: '360', stateAbbr: 'WA', state: 'Washington', region: 'Olympia, Vancouver, Bellingham (western Washington)' },
  { code: '361', stateAbbr: 'TX', state: 'Texas', region: 'Corpus Christi, Victoria (south Texas)' },
  { code: '363', stateAbbr: 'NY', state: 'New York', region: 'Nassau County (Hempstead, Mineola)' },
  { code: '364', stateAbbr: 'KY', state: 'Kentucky', region: 'Bowling Green, Owensboro, Paducah (western Kentucky)' },
  { code: '369', stateAbbr: 'CA', state: 'California', region: 'Vallejo, Santa Rosa, Eureka (northwestern California)' },
  { code: '380', stateAbbr: 'OH', state: 'Ohio', region: 'Columbus and Franklin County' },
  { code: '385', stateAbbr: 'UT', state: 'Utah', region: 'Salt Lake City, Ogden, Provo (Wasatch Front)' },
  { code: '386', stateAbbr: 'FL', state: 'Florida', region: 'Daytona Beach, Lake City (northeastern Florida)' },
  { code: '401', stateAbbr: 'RI', state: 'Rhode Island', region: 'all' },
  { code: '402', stateAbbr: 'NE', state: 'Nebraska', region: 'Omaha, Lincoln, Norfolk (eastern Nebraska)' },
  { code: '404', stateAbbr: 'GA', state: 'Georgia', region: 'Atlanta (inside I-285)' },
  { code: '405', stateAbbr: 'OK', state: 'Oklahoma', region: 'Oklahoma City, Norman, Edmond (central Oklahoma)' },
  { code: '406', stateAbbr: 'MT', state: 'Montana', region: 'all' },
  { code: '407', stateAbbr: 'FL', state: 'Florida', region: 'Orlando, Kissimmee, Sanford (east-central Florida)' },
  { code: '408', stateAbbr: 'CA', state: 'California', region: 'San Jose and Silicon Valley' },
  { code: '409', stateAbbr: 'TX', state: 'Texas', region: 'Beaumont, Galveston, Port Arthur' },
  { code: '410', stateAbbr: 'MD', state: 'Maryland', region: 'Baltimore, Annapolis (Chesapeake Bay area)' },
  { code: '412', stateAbbr: 'PA', state: 'Pennsylvania', region: 'Pittsburgh region' },
  { code: '413', stateAbbr: 'MA', state: 'Massachusetts', region: 'Western Massachusetts (Springfield)' },
  { code: '414', stateAbbr: 'WI', state: 'Wisconsin', region: 'Milwaukee County' },
  { code: '415', stateAbbr: 'CA', state: 'California', region: 'San Francisco and Marin County' },
  { code: '417', stateAbbr: 'MO', state: 'Missouri', region: 'Springfield, Joplin, Branson (southwestern Missouri)' },
  { code: '419', stateAbbr: 'OH', state: 'Ohio', region: 'Toledo area (northwestern Ohio)' },
  { code: '423', stateAbbr: 'TN', state: 'Tennessee', region: 'Chattanooga, Johnson City (East Tennessee)' },
  { code: '424', stateAbbr: 'CA', state: 'California', region: 'West/coastal Los Angeles County; Santa Catalina Island' },
  { code: '425', stateAbbr: 'WA', state: 'Washington', region: 'Bellevue, Everett (northern/eastern suburbs of Seattle)' },
  { code: '430', stateAbbr: 'TX', state: 'Texas', region: 'Tyler, Longview, Sherman (northeast Texas)' },
  { code: '432', stateAbbr: 'TX', state: 'Texas', region: 'Midland, Odessa (western Texas)' },
  { code: '434', stateAbbr: 'VA', state: 'Virginia', region: 'Charlottesville, Lynchburg, Danville (south-central Virginia)' },
  { code: '435', stateAbbr: 'UT', state: 'Utah', region: 'Utah outside the Wasatch Front metros' },
  { code: '436', stateAbbr: 'OH', state: 'Ohio', region: 'Elyria, Lorain, Ashtabula (north-central Ohio)' },
  { code: '440', stateAbbr: 'OH', state: 'Ohio', region: 'Elyria, Lorain, Ashtabula (surrounding Cleveland)' },
  { code: '442', stateAbbr: 'CA', state: 'California', region: 'Desert and mountain areas of southeastern California' },
  { code: '443', stateAbbr: 'MD', state: 'Maryland', region: 'Baltimore, Annapolis (Chesapeake Bay area)' },
  { code: '445', stateAbbr: 'PA', state: 'Pennsylvania', region: 'Philadelphia (overlay of 215/267)' },
  { code: '447', stateAbbr: 'IL', state: 'Illinois', region: 'Springfield, Champaign, Decatur (central Illinois)' },
  { code: '448', stateAbbr: 'FL', state: 'Florida', region: 'The Florida Panhandle' },
  { code: '457', stateAbbr: 'LA', state: 'Louisiana', region: 'Shreveport, Monroe, Alexandria (northern Louisiana)' },
  { code: '458', stateAbbr: 'OR', state: 'Oregon', region: 'Eugene, Medford, Bend (excludes Portland metro)' },
  { code: '463', stateAbbr: 'IN', state: 'Indiana', region: 'Indianapolis metro' },
  { code: '464', stateAbbr: 'IL', state: 'Illinois', region: 'Southern suburbs of Chicago (suburban Cook County)' },
  { code: '465', stateAbbr: 'NY', state: 'New York', region: 'New York City (Bronx, Brooklyn, Queens, Staten Island)' },
  { code: '469', stateAbbr: 'TX', state: 'Texas', region: 'Dallas metropolitan area' },
  { code: '470', stateAbbr: 'GA', state: 'Georgia', region: 'Atlanta metropolitan area' },
  { code: '471', stateAbbr: 'MS', state: 'Mississippi', region: 'Tupelo, Columbus, Greenville (northern Mississippi)' },
  { code: '472', stateAbbr: 'NC', state: 'North Carolina', region: 'Fayetteville, Wilmington, Jacksonville' },
  { code: '475', stateAbbr: 'CT', state: 'Connecticut', region: 'Bridgeport, New Haven, Waterbury (southwestern Connecticut)' },
  { code: '478', stateAbbr: 'GA', state: 'Georgia', region: 'Macon, Warner Robins (central Georgia)' },
  { code: '479', stateAbbr: 'AR', state: 'Arkansas', region: 'Fort Smith, Fayetteville, Rogers (northwestern Arkansas)' },
  { code: '480', stateAbbr: 'AZ', state: 'Arizona', region: 'Phoenix metro (East Valley)' },
  { code: '483', stateAbbr: 'AL', state: 'Alabama', region: 'Montgomery, Auburn, Dothan (southeastern Alabama)' },
  { code: '484', stateAbbr: 'PA', state: 'Pennsylvania', region: 'Allentown, Reading, Norristown (southeastern Pennsylvania)' },
  { code: '501', stateAbbr: 'AR', state: 'Arkansas', region: 'Little Rock, Hot Springs (central Arkansas)' },
  { code: '502', stateAbbr: 'KY', state: 'Kentucky', region: 'Louisville, Frankfort (north-central Kentucky)' },
  { code: '503', stateAbbr: 'OR', state: 'Oregon', region: 'Portland, Salem (northwestern Oregon)' },
  { code: '504', stateAbbr: 'LA', state: 'Louisiana', region: 'New Orleans metropolitan area' },
  { code: '505', stateAbbr: 'NM', state: 'New Mexico', region: 'Albuquerque, Santa Fe (northwestern/central New Mexico)' },
  { code: '507', stateAbbr: 'MN', state: 'Minnesota', region: 'Rochester, Mankato (southern Minnesota)' },
  { code: '508', stateAbbr: 'MA', state: 'Massachusetts', region: 'Southeastern Massachusetts (Worcester, New Bedford)' },
  { code: '509', stateAbbr: 'WA', state: 'Washington', region: 'Spokane, Tri-Cities, Yakima (eastern Washington)' },
  { code: '510', stateAbbr: 'CA', state: 'California', region: 'East Bay (Oakland, Fremont, Berkeley)' },
  { code: '512', stateAbbr: 'TX', state: 'Texas', region: 'Austin, San Marcos (central Texas)' },
  { code: '513', stateAbbr: 'OH', state: 'Ohio', region: 'Cincinnati area (southwestern Ohio)' },
  { code: '515', stateAbbr: 'IA', state: 'Iowa', region: 'Des Moines, Ames (north-central Iowa)' },
  { code: '516', stateAbbr: 'NY', state: 'New York', region: 'Nassau County (Hempstead, Mineola)' },
  { code: '517', stateAbbr: 'MI', state: 'Michigan', region: 'Lansing, Jackson (south-central Michigan)' },
  { code: '518', stateAbbr: 'NY', state: 'New York', region: 'Albany, Schenectady, Plattsburgh (northeastern NY)' },
  { code: '520', stateAbbr: 'AZ', state: 'Arizona', region: 'Tucson (southeastern Arizona)' },
  { code: '530', stateAbbr: 'CA', state: 'California', region: 'Redding, Chico, Davis, South Lake Tahoe (northern California)' },
  { code: '531', stateAbbr: 'NE', state: 'Nebraska', region: 'Omaha, Lincoln (eastern Nebraska)' },
  { code: '534', stateAbbr: 'WI', state: 'Wisconsin', region: 'Eau Claire, Wausau (northern Wisconsin)' },
  { code: '539', stateAbbr: 'OK', state: 'Oklahoma', region: 'Tulsa, Muskogee (northeastern Oklahoma)' },
  { code: '540', stateAbbr: 'VA', state: 'Virginia', region: 'Roanoke, Fredericksburg, Harrisonburg (north-central Virginia)' },
  { code: '541', stateAbbr: 'OR', state: 'Oregon', region: 'Eugene, Bend, Medford (Oregon outside Portland metro)' },
  { code: '551', stateAbbr: 'NJ', state: 'New Jersey', region: 'Bergen County and Hudson County' },
  { code: '557', stateAbbr: 'MO', state: 'Missouri', region: 'St. Louis and inner suburbs' },
  { code: '559', stateAbbr: 'CA', state: 'California', region: 'Fresno, Visalia (San Joaquin Valley)' },
  { code: '561', stateAbbr: 'FL', state: 'Florida', region: 'Palm Beach County (West Palm Beach, Boca Raton)' },
  { code: '562', stateAbbr: 'CA', state: 'California', region: 'Long Beach, Downey, Whittier (southeastern LA County)' },
  { code: '563', stateAbbr: 'IA', state: 'Iowa', region: 'Davenport, Dubuque (eastern/northeastern Iowa)' },
  { code: '564', stateAbbr: 'WA', state: 'Washington', region: 'Olympia, Vancouver, Bellingham (western Washington)' },
  { code: '567', stateAbbr: 'OH', state: 'Ohio', region: 'Toledo area (northwestern Ohio)' },
  { code: '570', stateAbbr: 'PA', state: 'Pennsylvania', region: 'Scranton, Wilkes-Barre, Williamsport (Wyoming Valley)' },
  { code: '571', stateAbbr: 'VA', state: 'Virginia', region: 'Northern Virginia (Arlington, Alexandria; D.C. suburbs)' },
  { code: '572', stateAbbr: 'OK', state: 'Oklahoma', region: 'Oklahoma City, Norman, Edmond (central Oklahoma)' },
  { code: '573', stateAbbr: 'MO', state: 'Missouri', region: 'Columbia, Jefferson City, Cape Girardeau' },
  { code: '574', stateAbbr: 'IN', state: 'Indiana', region: 'South Bend, Elkhart (north-central Indiana)' },
  { code: '575', stateAbbr: 'NM', state: 'New Mexico', region: 'Las Cruces, Roswell, Carlsbad (southern/eastern New Mexico)' },
  { code: '580', stateAbbr: 'OK', state: 'Oklahoma', region: 'Lawton, Enid, Ardmore (southern/western Oklahoma)' },
  { code: '582', stateAbbr: 'PA', state: 'Pennsylvania', region: 'Erie, State College, Altoona, Johnstown' },
  { code: '585', stateAbbr: 'NY', state: 'New York', region: 'Rochester, Batavia (western New York)' },
  { code: '586', stateAbbr: 'MI', state: 'Michigan', region: 'Macomb County' },
  { code: '601', stateAbbr: 'MS', state: 'Mississippi', region: 'Jackson, Hattiesburg, Meridian (central Mississippi)' },
  { code: '602', stateAbbr: 'AZ', state: 'Arizona', region: 'Phoenix metro (city of Phoenix)' },
  { code: '603', stateAbbr: 'NH', state: 'New Hampshire', region: 'all' },
  { code: '605', stateAbbr: 'SD', state: 'South Dakota', region: 'all' },
  { code: '606', stateAbbr: 'KY', state: 'Kentucky', region: 'Ashland, Pikeville, Somerset (eastern Kentucky)' },
  { code: '607', stateAbbr: 'NY', state: 'New York', region: 'Binghamton, Elmira, Ithaca (south-central New York)' },
  { code: '608', stateAbbr: 'WI', state: 'Wisconsin', region: 'Madison, La Crosse, Beloit (southwestern Wisconsin)' },
  { code: '609', stateAbbr: 'NJ', state: 'New Jersey', region: 'Trenton, Atlantic City, Princeton (central/southeastern New Jersey)' },
  { code: '610', stateAbbr: 'PA', state: 'Pennsylvania', region: 'Allentown, Reading, Norristown (southeastern Pennsylvania)' },
  { code: '612', stateAbbr: 'MN', state: 'Minnesota', region: 'Minneapolis, Richfield' },
  { code: '614', stateAbbr: 'OH', state: 'Ohio', region: 'Columbus and Franklin County' },
  { code: '615', stateAbbr: 'TN', state: 'Tennessee', region: 'Nashville (northern Middle Tennessee)' },
  { code: '616', stateAbbr: 'MI', state: 'Michigan', region: 'Grand Rapids, Holland (southwestern Michigan)' },
  { code: '617', stateAbbr: 'MA', state: 'Massachusetts', region: 'Boston and inner suburbs' },
  { code: '618', stateAbbr: 'IL', state: 'Illinois', region: 'Carbondale, Alton, Belleville (southern Illinois)' },
  { code: '619', stateAbbr: 'CA', state: 'California', region: 'San Diego and suburbs' },
  { code: '620', stateAbbr: 'KS', state: 'Kansas', region: 'Southern Kansas (excluding Wichita metro)' },
  { code: '621', stateAbbr: 'TX', state: 'Texas', region: 'Houston area' },
  { code: '623', stateAbbr: 'AZ', state: 'Arizona', region: 'Phoenix metro (West Valley)' },
  { code: '624', stateAbbr: 'NY', state: 'New York', region: 'Buffalo, Niagara Falls, Olean (western New York)' },
  { code: '626', stateAbbr: 'CA', state: 'California', region: 'San Gabriel Valley' },
  { code: '628', stateAbbr: 'CA', state: 'California', region: 'San Francisco and Marin County' },
  { code: '629', stateAbbr: 'TN', state: 'Tennessee', region: 'Nashville and surrounding area (Middle Tennessee)' },
  { code: '630', stateAbbr: 'IL', state: 'Illinois', region: 'Western suburbs of Chicago (DuPage County)' },
  { code: '631', stateAbbr: 'NY', state: 'New York', region: 'Suffolk County (Long Island)' },
  { code: '636', stateAbbr: 'MO', state: 'Missouri', region: 'St. Charles, Chesterfield (east-central Missouri)' },
  { code: '641', stateAbbr: 'IA', state: 'Iowa', region: 'Mason City, Ottumwa (central Iowa)' },
  { code: '645', stateAbbr: 'FL', state: 'Florida', region: 'Miami-Dade County and the Florida Keys' },
  { code: '646', stateAbbr: 'NY', state: 'New York', region: 'New York City (Manhattan)' },
  { code: '650', stateAbbr: 'CA', state: 'California', region: 'San Mateo, Palo Alto, Redwood City (Peninsula)' },
  { code: '651', stateAbbr: 'MN', state: 'Minnesota', region: 'St. Paul (east-central Minnesota)' },
  { code: '656', stateAbbr: 'FL', state: 'Florida', region: 'Tampa, Hillsborough County' },
  { code: '657', stateAbbr: 'CA', state: 'California', region: 'Northern Orange County (Anaheim, Santa Ana)' },
  { code: '659', stateAbbr: 'AL', state: 'Alabama', region: 'Birmingham, Tuscaloosa (western/central Alabama)' },
  { code: '660', stateAbbr: 'MO', state: 'Missouri', region: 'Sedalia, Kirksville (north-central Missouri)' },
  { code: '661', stateAbbr: 'CA', state: 'California', region: 'Bakersfield, Santa Clarita, Lancaster, Palmdale' },
  { code: '662', stateAbbr: 'MS', state: 'Mississippi', region: 'Tupelo, Columbus, Greenville (northern Mississippi)' },
  { code: '667', stateAbbr: 'MD', state: 'Maryland', region: 'Baltimore, Annapolis (Chesapeake Bay area)' },
  { code: '669', stateAbbr: 'CA', state: 'California', region: 'San Jose and Silicon Valley' },
  { code: '670', stateAbbr: 'MP', state: 'Northern Mariana Islands', region: 'Northern Mariana Islands (todo el territorio)' },
  { code: '671', stateAbbr: 'GU', state: 'Guam', region: 'Guam (incluye Andersen AFB)' },
  { code: '678', stateAbbr: 'GA', state: 'Georgia', region: 'Metro Atlanta' },
  { code: '679', stateAbbr: 'MI', state: 'Michigan', region: 'Detroit, Dearborn' },
  { code: '680', stateAbbr: 'NY', state: 'New York', region: 'Syracuse, Utica, Watertown (north-central NY)' },
  { code: '681', stateAbbr: 'WV', state: 'West Virginia', region: 'all' },
  { code: '682', stateAbbr: 'TX', state: 'Texas', region: 'Fort Worth, Arlington' },
  { code: '684', stateAbbr: 'AS', state: 'American Samoa', region: 'American Samoa (todo el territorio)' },
  { code: '686', stateAbbr: 'VA', state: 'Virginia', region: 'Richmond Metropolitan Area (Petersburg, Northern Neck)' },
  { code: '689', stateAbbr: 'FL', state: 'Florida', region: 'Orlando, Kissimmee (east-central Florida)' },
  { code: '701', stateAbbr: 'ND', state: 'North Dakota', region: 'all' },
  { code: '702', stateAbbr: 'NV', state: 'Nevada', region: 'Las Vegas Valley (Clark County)' },
  { code: '703', stateAbbr: 'VA', state: 'Virginia', region: 'Northern Virginia (Arlington, Fairfax; D.C. suburbs)' },
  { code: '704', stateAbbr: 'NC', state: 'North Carolina', region: 'Charlotte, Concord, Gastonia (south-central NC)' },
  { code: '706', stateAbbr: 'GA', state: 'Georgia', region: 'Athens, Augusta, Columbus, Rome (northern/eastern Georgia)' },
  { code: '707', stateAbbr: 'CA', state: 'California', region: 'Vallejo, Santa Rosa, Eureka (northwestern California)' },
  { code: '708', stateAbbr: 'IL', state: 'Illinois', region: 'Southern suburbs of Chicago (suburban Cook County)' },
  { code: '712', stateAbbr: 'IA', state: 'Iowa', region: 'Sioux City, Council Bluffs (western Iowa)' },
  { code: '713', stateAbbr: 'TX', state: 'Texas', region: 'Houston area' },
  { code: '714', stateAbbr: 'CA', state: 'California', region: 'Northern Orange County (Anaheim, Santa Ana, Huntington Beach)' },
  { code: '715', stateAbbr: 'WI', state: 'Wisconsin', region: 'Eau Claire, Wausau (northern Wisconsin)' },
  { code: '716', stateAbbr: 'NY', state: 'New York', region: 'Buffalo, Niagara Falls (western New York)' },
  { code: '717', stateAbbr: 'PA', state: 'Pennsylvania', region: 'Harrisburg, Lancaster, York (south-central Pennsylvania)' },
  { code: '718', stateAbbr: 'NY', state: 'New York', region: 'New York City (Bronx, Brooklyn, Queens, Staten Island)' },
  { code: '719', stateAbbr: 'CO', state: 'Colorado', region: 'Colorado Springs, Pueblo (southeastern Colorado)' },
  { code: '720', stateAbbr: 'CO', state: 'Colorado', region: 'Denver, Boulder, Aurora (central Colorado)' },
  { code: '724', stateAbbr: 'PA', state: 'Pennsylvania', region: 'Washington, Greensburg, New Castle (southwestern Pennsylvania)' },
  { code: '725', stateAbbr: 'NV', state: 'Nevada', region: 'Las Vegas Valley (Clark County)' },
  { code: '726', stateAbbr: 'TX', state: 'Texas', region: 'San Antonio metropolitan area' },
  { code: '727', stateAbbr: 'FL', state: 'Florida', region: 'Pinellas County (St. Petersburg, Clearwater)' },
  { code: '728', stateAbbr: 'FL', state: 'Florida', region: 'Palm Beach County (West Palm Beach, Boca Raton)' },
  { code: '729', stateAbbr: 'TN', state: 'Tennessee', region: 'Chattanooga, Johnson City (East Tennessee)' },
  { code: '730', stateAbbr: 'IL', state: 'Illinois', region: 'Carbondale, Alton, Belleville (southern Illinois)' },
  { code: '731', stateAbbr: 'TN', state: 'Tennessee', region: 'Jackson, Dyersburg (West Tennessee, excluding Memphis)' },
  { code: '732', stateAbbr: 'NJ', state: 'New Jersey', region: 'New Brunswick, Lakewood (east-central New Jersey)' },
  { code: '734', stateAbbr: 'MI', state: 'Michigan', region: 'Ann Arbor, Monroe, Ypsilanti (southwestern Detroit suburbs)' },
  { code: '737', stateAbbr: 'TX', state: 'Texas', region: 'Austin and suburbs' },
  { code: '738', stateAbbr: 'CA', state: 'California', region: 'Los Angeles (outside the San Fernando Valley)' },
  { code: '740', stateAbbr: 'OH', state: 'Ohio', region: 'Southeastern and central Ohio (Zanesville, Chillicothe)' },
  { code: '743', stateAbbr: 'NC', state: 'North Carolina', region: 'Piedmont Triad (Greensboro, Winston-Salem)' },
  { code: '747', stateAbbr: 'CA', state: 'California', region: 'San Fernando Valley (Burbank, Glendale, North Hollywood)' },
  { code: '748', stateAbbr: 'CO', state: 'Colorado', region: 'Western and northern Colorado' },
  { code: '754', stateAbbr: 'FL', state: 'Florida', region: 'Broward County (Fort Lauderdale, Hollywood)' },
  { code: '757', stateAbbr: 'VA', state: 'Virginia', region: 'Hampton Roads and the Eastern Shore' },
  { code: '760', stateAbbr: 'CA', state: 'California', region: 'Desert and mountain areas of southeastern California' },
  { code: '762', stateAbbr: 'GA', state: 'Georgia', region: 'Athens, Augusta, Columbus, Rome (northern/eastern Georgia)' },
  { code: '763', stateAbbr: 'MN', state: 'Minnesota', region: 'Brooklyn Park, Maple Grove (northwest Minneapolis suburbs)' },
  { code: '765', stateAbbr: 'IN', state: 'Indiana', region: 'Kokomo, Lafayette, Muncie, Richmond' },
  { code: '769', stateAbbr: 'MS', state: 'Mississippi', region: 'Jackson, Hattiesburg, Meridian (central Mississippi)' },
  { code: '770', stateAbbr: 'GA', state: 'Georgia', region: 'Atlanta suburbs (Marietta, Roswell, Lawrenceville)' },
  { code: '771', stateAbbr: 'DC', state: 'District of Columbia', region: 'Washington, D.C. (overlay de 202)' },
  { code: '772', stateAbbr: 'FL', state: 'Florida', region: 'Port St. Lucie, Vero Beach, Stuart (Treasure Coast)' },
  { code: '773', stateAbbr: 'IL', state: 'Illinois', region: 'City of Chicago (excluding downtown)' },
  { code: '774', stateAbbr: 'MA', state: 'Massachusetts', region: 'Southeastern Massachusetts (Worcester, New Bedford)' },
  { code: '775', stateAbbr: 'NV', state: 'Nevada', region: 'Reno, Carson City, Elko (Nevada outside Las Vegas)' },
  { code: '779', stateAbbr: 'IL', state: 'Illinois', region: 'Rockford, La Salle (northern Illinois outside Chicago)' },
  { code: '781', stateAbbr: 'MA', state: 'Massachusetts', region: 'Boston suburbs (east-central Massachusetts)' },
  { code: '785', stateAbbr: 'KS', state: 'Kansas', region: 'Topeka, Salina, Lawrence, Manhattan (northern/central Kansas)' },
  { code: '786', stateAbbr: 'FL', state: 'Florida', region: 'Miami-Dade County and the Florida Keys' },
  { code: '787', stateAbbr: 'PR', state: 'Puerto Rico', region: 'Puerto Rico (toda la isla)' },
  { code: '800', stateAbbr: '', state: 'No geográfico', region: 'Línea gratuita (toll-free)' },
  { code: '801', stateAbbr: 'UT', state: 'Utah', region: 'Salt Lake City, Ogden, Provo (Wasatch Front)' },
  { code: '802', stateAbbr: 'VT', state: 'Vermont', region: 'all' },
  { code: '803', stateAbbr: 'SC', state: 'South Carolina', region: 'Columbia, Rock Hill, Aiken (central South Carolina)' },
  { code: '804', stateAbbr: 'VA', state: 'Virginia', region: 'Richmond Metropolitan Area (Petersburg, Northern Neck)' },
  { code: '805', stateAbbr: 'CA', state: 'California', region: 'Ventura, San Luis Obispo, Santa Barbara Counties' },
  { code: '806', stateAbbr: 'TX', state: 'Texas', region: 'Lubbock, Amarillo (Texas Panhandle)' },
  { code: '808', stateAbbr: 'HI', state: 'Hawaii', region: 'all Hawaiian Islands (Honolulu, Hilo, Kahului)' },
  { code: '810', stateAbbr: 'MI', state: 'Michigan', region: 'Flint, Port Huron (the Michigan "Thumb")' },
  { code: '812', stateAbbr: 'IN', state: 'Indiana', region: 'Evansville, Bloomington, Terre Haute (southern Indiana)' },
  { code: '813', stateAbbr: 'FL', state: 'Florida', region: 'Tampa, Hillsborough County' },
  { code: '814', stateAbbr: 'PA', state: 'Pennsylvania', region: 'Erie, State College, Altoona, Johnstown' },
  { code: '815', stateAbbr: 'IL', state: 'Illinois', region: 'Rockford, La Salle (northern Illinois outside Chicago)' },
  { code: '816', stateAbbr: 'MO', state: 'Missouri', region: 'Kansas City, St. Joseph, Independence (west-central Missouri)' },
  { code: '817', stateAbbr: 'TX', state: 'Texas', region: 'Fort Worth, Arlington' },
  { code: '818', stateAbbr: 'CA', state: 'California', region: 'San Fernando Valley (Burbank, Glendale, North Hollywood)' },
  { code: '820', stateAbbr: 'CA', state: 'California', region: 'Ventura, San Luis Obispo, Santa Barbara Counties' },
  { code: '821', stateAbbr: 'SC', state: 'South Carolina', region: 'The Upstate (Greenville, Spartanburg, Anderson)' },
  { code: '826', stateAbbr: 'VA', state: 'Virginia', region: 'Roanoke, Fredericksburg, Harrisonburg (north-central Virginia)' },
  { code: '828', stateAbbr: 'NC', state: 'North Carolina', region: 'Asheville, Hickory (western North Carolina)' },
  { code: '830', stateAbbr: 'TX', state: 'Texas', region: 'New Braunfels, Del Rio, Kerrville, Eagle Pass' },
  { code: '831', stateAbbr: 'CA', state: 'California', region: 'Monterey, Salinas, Santa Cruz, Hollister' },
  { code: '832', stateAbbr: 'TX', state: 'Texas', region: 'Houston Metropolitan Area' },
  { code: '833', stateAbbr: '', state: 'No geográfico', region: 'Línea gratuita (toll-free)' },
  { code: '835', stateAbbr: 'PA', state: 'Pennsylvania', region: 'Allentown, Reading, Norristown (southeastern Pennsylvania)' },
  { code: '837', stateAbbr: 'CA', state: 'California', region: 'Redding, Chico, Davis, South Lake Tahoe (northern California)' },
  { code: '838', stateAbbr: 'NY', state: 'New York', region: 'Albany, Schenectady, Plattsburgh (northeastern NY)' },
  { code: '839', stateAbbr: 'SC', state: 'South Carolina', region: 'Columbia, Rock Hill, Aiken (central South Carolina)' },
  { code: '840', stateAbbr: 'CA', state: 'California', region: 'San Bernardino County (Fontana, Pomona)' },
  { code: '843', stateAbbr: 'SC', state: 'South Carolina', region: 'Charleston, Myrtle Beach, Hilton Head (southeastern SC)' },
  { code: '844', stateAbbr: '', state: 'No geográfico', region: 'Línea gratuita (toll-free)' },
  { code: '845', stateAbbr: 'NY', state: 'New York', region: 'Hudson Valley (Dutchess, Orange, Rockland, Ulster counties)' },
  { code: '847', stateAbbr: 'IL', state: 'Illinois', region: 'North and northwest suburbs of Chicago (Lake County)' },
  { code: '848', stateAbbr: 'NJ', state: 'New Jersey', region: 'New Brunswick, Lakewood (east-central New Jersey)' },
  { code: '850', stateAbbr: 'FL', state: 'Florida', region: 'Northwestern Florida (Pensacola, Tallahassee, Panama City)' },
  { code: '854', stateAbbr: 'SC', state: 'South Carolina', region: 'Charleston, Myrtle Beach, Hilton Head (southeastern SC)' },
  { code: '855', stateAbbr: '', state: 'No geográfico', region: 'Línea gratuita (toll-free)' },
  { code: '856', stateAbbr: 'NJ', state: 'New Jersey', region: 'Camden, Cherry Hill, Vineland (southwestern New Jersey)' },
  { code: '857', stateAbbr: 'MA', state: 'Massachusetts', region: 'Boston and inner suburbs' },
  { code: '858', stateAbbr: 'CA', state: 'California', region: 'San Diego and suburbs' },
  { code: '859', stateAbbr: 'KY', state: 'Kentucky', region: 'Lexington, Covington, Florence (northern Kentucky)' },
  { code: '860', stateAbbr: 'CT', state: 'Connecticut', region: 'Hartford, Norwich (northern/eastern Connecticut)' },
  { code: '861', stateAbbr: 'IL', state: 'Illinois', region: 'Peoria, Bloomington, Moline (west-central Illinois)' },
  { code: '862', stateAbbr: 'NJ', state: 'New Jersey', region: 'Newark, Paterson (northeastern New Jersey)' },
  { code: '863', stateAbbr: 'FL', state: 'Florida', region: 'Lakeland, Winter Haven, Sebring (south-central Florida)' },
  { code: '864', stateAbbr: 'SC', state: 'South Carolina', region: 'The Upstate (Greenville, Spartanburg, Anderson)' },
  { code: '865', stateAbbr: 'TN', state: 'Tennessee', region: 'Knoxville, Oak Ridge (East Tennessee)' },
  { code: '866', stateAbbr: '', state: 'No geográfico', region: 'Línea gratuita (toll-free)' },
  { code: '870', stateAbbr: 'AR', state: 'Arkansas', region: 'Texarkana, Jonesboro, Pine Bluff (southern/eastern Arkansas)' },
  { code: '872', stateAbbr: 'IL', state: 'Illinois', region: 'Chicago' },
  { code: '877', stateAbbr: '', state: 'No geográfico', region: 'Línea gratuita (toll-free)' },
  { code: '878', stateAbbr: 'PA', state: 'Pennsylvania', region: 'Pittsburgh region' },
  { code: '888', stateAbbr: '', state: 'No geográfico', region: 'Línea gratuita (toll-free)' },
  { code: '900', stateAbbr: '', state: 'No geográfico', region: 'Tarifa premium' },
  { code: '901', stateAbbr: 'TN', state: 'Tennessee', region: 'Memphis (Shelby County)' },
  { code: '903', stateAbbr: 'TX', state: 'Texas', region: 'Tyler, Longview, Sherman (northeast Texas)' },
  { code: '904', stateAbbr: 'FL', state: 'Florida', region: 'Jacksonville, St. Augustine (northeastern Florida)' },
  { code: '906', stateAbbr: 'MI', state: 'Michigan', region: 'Upper Peninsula (Marquette, Sault Ste. Marie)' },
  { code: '907', stateAbbr: 'AK', state: 'Alaska', region: 'all Alaska' },
  { code: '908', stateAbbr: 'NJ', state: 'New Jersey', region: 'Elizabeth, Plainfield (west-central New Jersey)' },
  { code: '909', stateAbbr: 'CA', state: 'California', region: 'San Bernardino County (Fontana, Pomona)' },
  { code: '910', stateAbbr: 'NC', state: 'North Carolina', region: 'Fayetteville, Wilmington, Fort Bragg' },
  { code: '912', stateAbbr: 'GA', state: 'Georgia', region: 'Savannah, Statesboro, Brunswick (southeastern Georgia)' },
  { code: '913', stateAbbr: 'KS', state: 'Kansas', region: 'Kansas City, Overland Park, Olathe (eastern Kansas)' },
  { code: '914', stateAbbr: 'NY', state: 'New York', region: 'Westchester County' },
  { code: '915', stateAbbr: 'TX', state: 'Texas', region: 'El Paso' },
  { code: '916', stateAbbr: 'CA', state: 'California', region: 'Sacramento Metropolitan Area' },
  { code: '917', stateAbbr: 'NY', state: 'New York', region: 'New York City (all boroughs; mainly mobile)' },
  { code: '918', stateAbbr: 'OK', state: 'Oklahoma', region: 'Tulsa, Muskogee (northeastern Oklahoma)' },
  { code: '919', stateAbbr: 'NC', state: 'North Carolina', region: 'Research Triangle (Raleigh, Durham, Cary, Chapel Hill)' },
  { code: '920', stateAbbr: 'WI', state: 'Wisconsin', region: 'Green Bay, Appleton, Oshkosh (eastern Wisconsin)' },
  { code: '925', stateAbbr: 'CA', state: 'California', region: 'Inland East Bay (Concord, Walnut Creek, Livermore)' },
  { code: '928', stateAbbr: 'AZ', state: 'Arizona', region: 'Arizona outside Phoenix/Tucson (Flagstaff, Yuma)' },
  { code: '929', stateAbbr: 'NY', state: 'New York', region: 'New York City (Bronx, Brooklyn, Queens, Staten Island)' },
  { code: '930', stateAbbr: 'IN', state: 'Indiana', region: 'Evansville, Bloomington, Terre Haute (southern Indiana)' },
  { code: '931', stateAbbr: 'TN', state: 'Tennessee', region: 'Clarksville, Columbia (southern Middle Tennessee)' },
  { code: '934', stateAbbr: 'NY', state: 'New York', region: 'Suffolk County (Long Island)' },
  { code: '936', stateAbbr: 'TX', state: 'Texas', region: 'Conroe, Huntsville, Lufkin, Nacogdoches (Southeast Texas)' },
  { code: '937', stateAbbr: 'OH', state: 'Ohio', region: 'Dayton, Springfield (southwestern Ohio)' },
  { code: '938', stateAbbr: 'AL', state: 'Alabama', region: 'Huntsville, Decatur, Gadsden (northern Alabama)' },
  { code: '939', stateAbbr: 'PR', state: 'Puerto Rico', region: 'Puerto Rico (overlay de 787)' },
  { code: '940', stateAbbr: 'TX', state: 'Texas', region: 'Denton, Wichita Falls (north of Dallas-Fort Worth)' },
  { code: '941', stateAbbr: 'FL', state: 'Florida', region: 'Sarasota, Bradenton, Port Charlotte (Gulf Coast south of Tampa)' },
  { code: '943', stateAbbr: 'GA', state: 'Georgia', region: 'Metro Atlanta' },
  { code: '945', stateAbbr: 'TX', state: 'Texas', region: 'Dallas-Fort Worth metroplex' },
  { code: '947', stateAbbr: 'MI', state: 'Michigan', region: 'Oakland County' },
  { code: '948', stateAbbr: 'VA', state: 'Virginia', region: 'Hampton Roads and the Eastern Shore' },
  { code: '949', stateAbbr: 'CA', state: 'California', region: 'Southern Orange County (Irvine, Mission Viejo, San Clemente)' },
  { code: '951', stateAbbr: 'CA', state: 'California', region: 'Western Riverside County (Riverside, Corona, Temecula)' },
  { code: '952', stateAbbr: 'MN', state: 'Minnesota', region: 'Bloomington, Edina, Eden Prairie (southwest Minneapolis suburbs)' },
  { code: '954', stateAbbr: 'FL', state: 'Florida', region: 'Broward County (Fort Lauderdale, Hollywood, Coral Springs)' },
  { code: '956', stateAbbr: 'TX', state: 'Texas', region: 'Laredo, McAllen, Brownsville (southmost Texas)' },
  { code: '959', stateAbbr: 'CT', state: 'Connecticut', region: 'Hartford, Norwich (northern/eastern Connecticut)' },
  { code: '970', stateAbbr: 'CO', state: 'Colorado', region: 'Fort Collins, Greeley, Grand Junction, Aspen (northern/western Colorado)' },
  { code: '971', stateAbbr: 'OR', state: 'Oregon', region: 'Portland, Salem (northwestern Oregon)' },
  { code: '972', stateAbbr: 'TX', state: 'Texas', region: 'Dallas metropolitan area' },
  { code: '973', stateAbbr: 'NJ', state: 'New Jersey', region: 'Newark, Paterson (northeastern New Jersey)' },
  { code: '978', stateAbbr: 'MA', state: 'Massachusetts', region: 'Northeastern Massachusetts (Lowell, Lawrence)' },
  { code: '979', stateAbbr: 'TX', state: 'Texas', region: 'College Station, Bryan, Lake Jackson (southeastern Texas)' },
  { code: '980', stateAbbr: 'NC', state: 'North Carolina', region: 'Charlotte, Concord, Gastonia (south-central NC)' },
  { code: '983', stateAbbr: 'CO', state: 'Colorado', region: 'Denver, Colorado' },
  { code: '984', stateAbbr: 'NC', state: 'North Carolina', region: 'Research Triangle (Raleigh, Durham, Cary, Chapel Hill)' },
  { code: '985', stateAbbr: 'LA', state: 'Louisiana', region: 'Houma, Slidell (southeastern Louisiana, excluding New Orleans)' },
  { code: '986', stateAbbr: 'ID', state: 'Idaho', region: 'all Idaho' },
  { code: '989', stateAbbr: 'MI', state: 'Michigan', region: 'Saginaw, Bay City, Midland, Mt. Pleasant (central Michigan)' },
]

const AREA_CODE_MAP = new Map(AREA_CODES.map((a) => [a.code, a]))

export function lookupAreaCode(code: string): AreaCode | undefined {
  return AREA_CODE_MAP.get(code)
}

export interface PhoneParse {
  /** Dígitos nacionales (sin el +1). */
  national: string
  /** Los 3 dígitos del area code, o null si no hay suficientes dígitos. */
  areaCode: string | null
  /** true si el número nacional tiene exactamente 10 dígitos. */
  complete: boolean
}

/** Extrae el area code de un teléfono en cualquier formato (+1, guiones, espacios, paréntesis). */
export function parsePhone(raw: string): PhoneParse {
  const digits = raw.replace(/\D/g, '')
  let national = digits
  // Quita el indicativo país +1 si viene con 11 dígitos
  if (national.length === 11 && national.startsWith('1')) {
    national = national.slice(1)
  }
  const areaCode = national.length >= 3 ? national.slice(0, 3) : null
  return { national, areaCode, complete: national.length === 10 }
}

/** ¿El code es no-geográfico (toll-free / premium)? */
export function isNonGeographic(area?: AreaCode): boolean {
  return !!area && area.stateAbbr === ''
}
